import { createCipheriv,createECDH,createPrivateKey,createSign,createHmac,randomBytes } from "node:crypto";
type Sub={endpoint:string;keys:{p256dh:string;auth:string}};
export type PushPayload={title:string;body:string;url?:string;tag?:string;renotify?:boolean;actions?:Array<{action:string;title:string}>};
const b64=(b:Buffer|Uint8Array)=>Buffer.from(b).toString("base64").replace(/\+/g,"-").replace(/\//g,"_").replace(/=+$/g,"");
const dec=(s:string)=>Buffer.from(s.replace(/-/g,"+").replace(/_/g,"/")+"=".repeat((4-s.length%4)%4),"base64");
const extract=(salt:Buffer,ikm:Buffer)=>createHmac("sha256",salt).update(ikm).digest();
function expand(prk:Buffer,info:Buffer,len:number){let out=Buffer.alloc(0),prev=Buffer.alloc(0);for(let i=1;out.length<len;i++){prev=createHmac("sha256",prk).update(Buffer.concat([prev,info,Buffer.from([i])])).digest();out=Buffer.concat([out,prev]);}return out.subarray(0,len);}
function keys(){const pub=process.env.VAPID_PUBLIC_KEY,priv=process.env.VAPID_PRIVATE_KEY,subject=process.env.VAPID_SUBJECT;if(!pub||!priv||!subject)throw new Error("VAPID yapılandırması eksik");const d=dec(priv);if(d.length!==32)throw new Error("VAPID_PRIVATE_KEY geçersiz");const e=createECDH("prime256v1");e.setPrivateKey(d);const p=e.getPublicKey(undefined,"uncompressed");if(b64(p)!==pub)throw new Error("VAPID anahtarları eşleşmiyor");return{pub,d,subject};}
function jwt(aud:string){const {pub,d,subject}=keys();const e=createECDH("prime256v1");e.setPrivateKey(d);const p=e.getPublicKey(undefined,"uncompressed");const key=createPrivateKey({key:{kty:"EC",crv:"P-256",x:b64(p.subarray(1,33)),y:b64(p.subarray(33,65)),d:b64(d)},format:"jwk"});const h=b64(Buffer.from(JSON.stringify({typ:"JWT",alg:"ES256"}))),pl=b64(Buffer.from(JSON.stringify({aud,exp:Math.floor(Date.now()/1000)+43200,sub:subject}))),input=h+"."+pl,s=createSign("SHA256");s.update(input);s.end();return input+"."+b64(s.sign({key,dsaEncoding:"ieee-p1363"}));}
function encrypt(sub:Sub,payload:PushPayload){const ua=dec(sub.keys.p256dh),auth=dec(sub.keys.auth);if(ua.length!==65||ua[0]!==4||auth.length!==16)throw new Error("Push anahtarları geçersiz");const e=createECDH("prime256v1");e.generateKeys();const as=e.getPublicKey(undefined,"uncompressed"),secret=e.computeSecret(ua),info=Buffer.concat([Buffer.from("WebPush: info"),Buffer.from([0]),ua,as]),ikm=expand(extract(auth,secret),info,32),salt=randomBytes(16),prk=extract(salt,ikm),cek=expand(prk,Buffer.concat([Buffer.from("Content-Encoding: aes128gcm"),Buffer.from([0])]),16),nonce=expand(prk,Buffer.concat([Buffer.from("Content-Encoding: nonce"),Buffer.from([0])]),12),plain=Buffer.concat([Buffer.from(JSON.stringify(payload)),Buffer.from([2])]),c=createCipheriv("aes-128-gcm",cek,nonce),cipher=Buffer.concat([c.update(plain),c.final(),c.getAuthTag()]),rs=Buffer.alloc(4);rs.writeUInt32BE(4096);return Buffer.concat([salt,rs,as,cipher]);}
export async function sendWebPush(sub:Sub,payload:PushPayload){const u=new URL(sub.endpoint),body=encrypt(sub,payload),r=await fetch(sub.endpoint,{method:"POST",headers:{Authorization:`vapid t=${jwt(u.origin)}, k=${keys().pub}`,TTL:"60",Urgency:"normal","Content-Type":"application/octet-stream","Content-Encoding":"aes128gcm"},body});return{status:r.status,body:await r.text()};}
export const isVapidConfigured=()=>Boolean(process.env.VAPID_PUBLIC_KEY&&process.env.VAPID_PRIVATE_KEY&&process.env.VAPID_SUBJECT);